services:


  cache:
    build: ./app/images/redis/
    restart: always

  daphne:
    build: ./app/images/daphne/
    volumes:
      - /venv                             # It doesnt recompile everytime we just Stop & Run it again
      - daphne_socket:/app/game_config/   #
    environment:
      - DJANGO_SETTINGS_MODULE=game_config.settings.local
    depends_on:
      - cache
    restart: always


  nginx:
    build: ./app/images/nginx/
    volumes:
      - daphne_socket:/sock
      - ./app/images/daphne/srcs:/app       # 
    ports:
      - "8080:80"
      - "443:443"
    restart: always



volumes:
  daphne_socket: